struct InputVS {
    float4 Position : POSITION;
};

struct OutputVS {
    float4 Position : POSITION;
    float2 TexCoord : TEXCOORD0;
};

struct OutputPS {
    float4 Color    : COLOR0;
};

uniform float4x4 wvp;

OutputVS main_vertex(InputVS In) {
    OutputVS Out;
    Out.Position = mul(In.Position, wvp);
    Out.TexCoord = In.Position.xy * 0.5f + 0.5f;
    return Out;
}


OutputPS main_fragment(OutputVS In) {
    OutputPS Out;
    Out.Color = float4(In.TexCoord.xy, 0.0f, 1.0f);
    return Out;
}


