
#ifndef _SDL_COLOR_EXT_H_
#define _SDL_COLOR_EXT_H_

#include <wee/wee.hpp>
#include <stdint.h>
#include <SDL.h>

#define SDL_COLOR_(x) SDL_Color { (x & 0x00ff0000) >> 16, (x & 0x0000ff00) >> 8, (x & 0x000000ff), 0xff };

struct SDL_Color;

void SDL_CreateColorEXT(uint32_t, struct SDL_Color*);
void SDL_CreateColorRGB(uint8_t, uint8_t, uint8_t, struct SDL_Color*);
void SDL_CreateColorHSV(uint8_t, uint8_t, uint8_t, struct SDL_Color*);



struct SDL_ColorPresetEXT {
	constexpr static const SDL_Color SDL_ColorPresetEXT::AliceBlue =  SDL_COLOR_(0xF0F8FF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::AntiqueWhite =  SDL_COLOR_(0xFAEBD7);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Aqua =  SDL_COLOR_(0x00FFFF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Aquamarine =  SDL_COLOR_(0x7FFFD4);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Azure =  SDL_COLOR_(0xF0FFFF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Beige =  SDL_COLOR_(0xF5F5DC);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Bisque =  SDL_COLOR_(0xFFE4C4);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Black =  SDL_COLOR_(0x000000);
	constexpr static const SDL_Color SDL_ColorPresetEXT::BlanchedAlmond =  SDL_COLOR_(0xFFEBCD);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Blue =  SDL_COLOR_(0x0000FF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::BlueViolet =  SDL_COLOR_(0x8A2BE2);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Brown =  SDL_COLOR_(0xA52A2A);
	constexpr static const SDL_Color SDL_ColorPresetEXT::BurlyWood =  SDL_COLOR_(0xDEB887);
	constexpr static const SDL_Color SDL_ColorPresetEXT::CadetBlue =  SDL_COLOR_(0x5F9EA0);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Chartreuse =  SDL_COLOR_(0x7FFF00);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Chocolate =  SDL_COLOR_(0xD2691E);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Coral =  SDL_COLOR_(0xFF7F50);
	constexpr static const SDL_Color SDL_ColorPresetEXT::CornflowerBlue =  SDL_COLOR_(0x6495ED);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Cornsilk =  SDL_COLOR_(0xFFF8DC);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Crimson =  SDL_COLOR_(0xDC143C);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Cyan =  SDL_COLOR_(0x00FFFF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkBlue =  SDL_COLOR_(0x00008B);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkCyan =  SDL_COLOR_(0x008B8B);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkGoldenRod =  SDL_COLOR_(0xB8860B);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkGray =  SDL_COLOR_(0xA9A9A9);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkGrey =  SDL_COLOR_(0xA9A9A9);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkGreen =  SDL_COLOR_(0x006400);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkKhaki =  SDL_COLOR_(0xBDB76B);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkMagenta =  SDL_COLOR_(0x8B008B);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkOliveGreen =  SDL_COLOR_(0x556B2F);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkOrange =  SDL_COLOR_(0xFF8C00);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkOrchid =  SDL_COLOR_(0x9932CC);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkRed =  SDL_COLOR_(0x8B0000);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkSalmon =  SDL_COLOR_(0xE9967A);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkSeaGreen =  SDL_COLOR_(0x8FBC8F);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkSlateBlue =  SDL_COLOR_(0x483D8B);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkSlateGray =  SDL_COLOR_(0x2F4F4F);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkSlateGrey =  SDL_COLOR_(0x2F4F4F);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkTurquoise =  SDL_COLOR_(0x00CED1);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DarkViolet =  SDL_COLOR_(0x9400D3);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DeepPink =  SDL_COLOR_(0xFF1493);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DeepSkyBlue =  SDL_COLOR_(0x00BFFF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DimGray =  SDL_COLOR_(0x696969);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DimGrey =  SDL_COLOR_(0x696969);
	constexpr static const SDL_Color SDL_ColorPresetEXT::DodgerBlue =  SDL_COLOR_(0x1E90FF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::FireBrick =  SDL_COLOR_(0xB22222);
	constexpr static const SDL_Color SDL_ColorPresetEXT::FloralWhite =  SDL_COLOR_(0xFFFAF0);
	constexpr static const SDL_Color SDL_ColorPresetEXT::ForestGreen =  SDL_COLOR_(0x228B22);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Fuchsia =  SDL_COLOR_(0xFF00FF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Gainsboro =  SDL_COLOR_(0xDCDCDC);
	constexpr static const SDL_Color SDL_ColorPresetEXT::GhostWhite =  SDL_COLOR_(0xF8F8FF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Gold =  SDL_COLOR_(0xFFD700);
	constexpr static const SDL_Color SDL_ColorPresetEXT::GoldenRod =  SDL_COLOR_(0xDAA520);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Gray =  SDL_COLOR_(0x808080);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Grey =  SDL_COLOR_(0x808080);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Green =  SDL_COLOR_(0x008000);
	constexpr static const SDL_Color SDL_ColorPresetEXT::GreenYellow =  SDL_COLOR_(0xADFF2F);
	constexpr static const SDL_Color SDL_ColorPresetEXT::HoneyDew =  SDL_COLOR_(0xF0FFF0);
	constexpr static const SDL_Color SDL_ColorPresetEXT::HotPink =  SDL_COLOR_(0xFF69B4);
	constexpr static const SDL_Color SDL_ColorPresetEXT::IndianRed =  SDL_COLOR_(0xCD5C5C);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Indigo =  SDL_COLOR_(0x4B0082);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Ivory =  SDL_COLOR_(0xFFFFF0);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Khaki =  SDL_COLOR_(0xF0E68C);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Lavender =  SDL_COLOR_(0xE6E6FA);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LavenderBlush =  SDL_COLOR_(0xFFF0F5);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LawnGreen =  SDL_COLOR_(0x7CFC00);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LemonChiffon =  SDL_COLOR_(0xFFFACD);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightBlue =  SDL_COLOR_(0xADD8E6);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightCoral =  SDL_COLOR_(0xF08080);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightCyan =  SDL_COLOR_(0xE0FFFF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightGoldenRodYellow =  SDL_COLOR_(0xFAFAD2);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightGray =  SDL_COLOR_(0xD3D3D3);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightGrey =  SDL_COLOR_(0xD3D3D3);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightGreen =  SDL_COLOR_(0x90EE90);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightPink =  SDL_COLOR_(0xFFB6C1);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightSalmon =  SDL_COLOR_(0xFFA07A);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightSeaGreen =  SDL_COLOR_(0x20B2AA);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightSkyBlue =  SDL_COLOR_(0x87CEFA);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightSlateGray =  SDL_COLOR_(0x778899);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightSlateGrey =  SDL_COLOR_(0x778899);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightSteelBlue =  SDL_COLOR_(0xB0C4DE);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LightYellow =  SDL_COLOR_(0xFFFFE0);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Lime =  SDL_COLOR_(0x00FF00);
	constexpr static const SDL_Color SDL_ColorPresetEXT::LimeGreen =  SDL_COLOR_(0x32CD32);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Linen =  SDL_COLOR_(0xFAF0E6);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Magenta =  SDL_COLOR_(0xFF00FF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Maroon =  SDL_COLOR_(0x800000);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MediumAquaMarine =  SDL_COLOR_(0x66CDAA);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MediumBlue =  SDL_COLOR_(0x0000CD);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MediumOrchid =  SDL_COLOR_(0xBA55D3);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MediumPurple =  SDL_COLOR_(0x9370DB);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MediumSeaGreen =  SDL_COLOR_(0x3CB371);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MediumSlateBlue =  SDL_COLOR_(0x7B68EE);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MediumSpringGreen =  SDL_COLOR_(0x00FA9A);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MediumTurquoise =  SDL_COLOR_(0x48D1CC);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MediumVioletRed =  SDL_COLOR_(0xC71585);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MidnightBlue =  SDL_COLOR_(0x191970);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MintCream =  SDL_COLOR_(0xF5FFFA);
	constexpr static const SDL_Color SDL_ColorPresetEXT::MistyRose =  SDL_COLOR_(0xFFE4E1);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Moccasin =  SDL_COLOR_(0xFFE4B5);
	constexpr static const SDL_Color SDL_ColorPresetEXT::NavajoWhite =  SDL_COLOR_(0xFFDEAD);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Navy =  SDL_COLOR_(0x000080);
	constexpr static const SDL_Color SDL_ColorPresetEXT::OldLace =  SDL_COLOR_(0xFDF5E6);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Olive =  SDL_COLOR_(0x808000);
	constexpr static const SDL_Color SDL_ColorPresetEXT::OliveDrab =  SDL_COLOR_(0x6B8E23);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Orange =  SDL_COLOR_(0xFFA500);
	constexpr static const SDL_Color SDL_ColorPresetEXT::OrangeRed =  SDL_COLOR_(0xFF4500);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Orchid =  SDL_COLOR_(0xDA70D6);
	constexpr static const SDL_Color SDL_ColorPresetEXT::PaleGoldenRod =  SDL_COLOR_(0xEEE8AA);
	constexpr static const SDL_Color SDL_ColorPresetEXT::PaleGreen =  SDL_COLOR_(0x98FB98);
	constexpr static const SDL_Color SDL_ColorPresetEXT::PaleTurquoise =  SDL_COLOR_(0xAFEEEE);
	constexpr static const SDL_Color SDL_ColorPresetEXT::PaleVioletRed =  SDL_COLOR_(0xDB7093);
	constexpr static const SDL_Color SDL_ColorPresetEXT::PapayaWhip =  SDL_COLOR_(0xFFEFD5);
	constexpr static const SDL_Color SDL_ColorPresetEXT::PeachPuff =  SDL_COLOR_(0xFFDAB9);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Peru =  SDL_COLOR_(0xCD853F);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Pink =  SDL_COLOR_(0xFFC0CB);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Plum =  SDL_COLOR_(0xDDA0DD);
	constexpr static const SDL_Color SDL_ColorPresetEXT::PowderBlue =  SDL_COLOR_(0xB0E0E6);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Purple =  SDL_COLOR_(0x800080);
	constexpr static const SDL_Color SDL_ColorPresetEXT::RebeccaPurple =  SDL_COLOR_(0x663399);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Red =  SDL_COLOR_(0xFF0000);
	constexpr static const SDL_Color SDL_ColorPresetEXT::RosyBrown =  SDL_COLOR_(0xBC8F8F);
	constexpr static const SDL_Color SDL_ColorPresetEXT::RoyalBlue =  SDL_COLOR_(0x4169E1);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SaddleBrown =  SDL_COLOR_(0x8B4513);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Salmon =  SDL_COLOR_(0xFA8072);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SandyBrown =  SDL_COLOR_(0xF4A460);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SeaGreen =  SDL_COLOR_(0x2E8B57);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SeaShell =  SDL_COLOR_(0xFFF5EE);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Sienna =  SDL_COLOR_(0xA0522D);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Silver =  SDL_COLOR_(0xC0C0C0);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SkyBlue =  SDL_COLOR_(0x87CEEB);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SlateBlue =  SDL_COLOR_(0x6A5ACD);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SlateGray =  SDL_COLOR_(0x708090);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SlateGrey =  SDL_COLOR_(0x708090);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Snow =  SDL_COLOR_(0xFFFAFA);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SpringGreen =  SDL_COLOR_(0x00FF7F);
	constexpr static const SDL_Color SDL_ColorPresetEXT::SteelBlue =  SDL_COLOR_(0x4682B4);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Tan =  SDL_COLOR_(0xD2B48C);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Teal =  SDL_COLOR_(0x008080);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Thistle =  SDL_COLOR_(0xD8BFD8);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Tomato =  SDL_COLOR_(0xFF6347);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Turquoise =  SDL_COLOR_(0x40E0D0);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Violet =  SDL_COLOR_(0xEE82EE);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Wheat =  SDL_COLOR_(0xF5DEB3);
	constexpr static const SDL_Color SDL_ColorPresetEXT::White =  SDL_COLOR_(0xFFFFFF);
	constexpr static const SDL_Color SDL_ColorPresetEXT::WhiteSmoke =  SDL_COLOR_(0xF5F5F5);
	constexpr static const SDL_Color SDL_ColorPresetEXT::Yellow =  SDL_COLOR_(0xFFFF00);
	constexpr static const SDL_Color SDL_ColorPresetEXT::YellowGreen =  SDL_COLOR_(0x9ACD32);

};
#endif
