
#ifndef _SDL_COLOR_EXT_H_
#define _SDL_COLOR_EXT_H_

#include <wee/wee.h>
#include <stdint.h>

struct SDL_Color;

C_API void SDL_CreateColorEXT(uint32_t, struct SDL_Color*);
C_API SDL_Color SDL_CreateColorRGB(uint8_t, uint8_t, uint8_t);
C_API SDL_Color SDL_CreateColorHSV(uint8_t, uint8_t, uint8_t);

struct SDL_ColorPresetEXT {

    static const SDL_Color* AliceBlue;
    static const SDL_Color* AntiqueWhite;
    static const SDL_Color* Aqua;
    static const SDL_Color* Aquamarine;
    static const SDL_Color* Azure;
    static const SDL_Color* Beige;
    static const SDL_Color* Bisque;
    static const SDL_Color* Black;
    static const SDL_Color* BlanchedAlmond  ;
    static const SDL_Color* Blue            ;
    static const SDL_Color* BlueViolet      ;
    static const SDL_Color* Brown           ;
    static const SDL_Color* BurlyWood       ;
    static const SDL_Color* CadetBlue       ;
    static const SDL_Color* Chartreuse      ;
    static const SDL_Color* Chocolate       ;
    static const SDL_Color* Coral           ;
    static const SDL_Color* CornflowerBlue  ;
    static const SDL_Color* Cornsilk        ;
    static const SDL_Color* Crimson         ;
    static const SDL_Color* Cyan            ;
    static const SDL_Color* DarkBlue        ;
    static const SDL_Color* DarkCyan        ;
    static const SDL_Color* DarkGoldenRod   ;
    static const SDL_Color* DarkGray        ;
    static const SDL_Color* DarkGrey        ;
    static const SDL_Color* DarkGreen       ;
    static const SDL_Color* DarkKhaki       ;
    static const SDL_Color* DarkMagenta     ;
    static const SDL_Color* DarkOliveGreen  ;
    static const SDL_Color* DarkOrange      ;
    static const SDL_Color* DarkOrchid      ;
    static const SDL_Color* DarkRed         ;
    static const SDL_Color* DarkSalmon      ;
    static const SDL_Color* DarkSeaGreen    ;
    static const SDL_Color* DarkSlateBlue   ;
    static const SDL_Color* DarkSlateGray   ;
    static const SDL_Color* DarkSlateGrey   ;
    static const SDL_Color* DarkTurquoise   ;
    static const SDL_Color* DarkViolet      ;
    static const SDL_Color* DeepPink        ;
    static const SDL_Color* DeepSkyBlue     ;
    static const SDL_Color* DimGray         ;
    static const SDL_Color* DimGrey         ;
    static const SDL_Color* DodgerBlue      ;
    static const SDL_Color* FireBrick       ;
    static const SDL_Color* FloralWhite     ;
    static const SDL_Color* ForestGreen     ;
    static const SDL_Color* Fuchsia         ;
    static const SDL_Color* Gainsboro       ;
    static const SDL_Color* GhostWhite      ;
    static const SDL_Color* Gold            ;
    static const SDL_Color* GoldenRod       ;
    static const SDL_Color* Gray            ;
    static const SDL_Color* Grey            ;
    static const SDL_Color* Green           ;
    static const SDL_Color* GreenYellow     ;
    static const SDL_Color* HoneyDew        ;
    static const SDL_Color* HotPink         ;
    static const SDL_Color* IndianRed       ;
    static const SDL_Color* Indigo          ;
    static const SDL_Color* Ivory           ;
    static const SDL_Color* Khaki           ;
    static const SDL_Color* Lavender        ;
    static const SDL_Color* LavenderBlush   ;
    static const SDL_Color* LawnGreen       ;
    static const SDL_Color* LemonChiffon    ;
    static const SDL_Color* LightBlue       ;
    static const SDL_Color* LightCoral      ;
    static const SDL_Color* LightCyan       ;
    static const SDL_Color* LightGoldenRodYellow; 
    static const SDL_Color* LightGray       ;
    static const SDL_Color* LightGrey       ;
    static const SDL_Color* LightGreen      ;
    static const SDL_Color* LightPink       ;
    static const SDL_Color* LightSalmon     ;
    static const SDL_Color* LightSeaGreen   ;
    static const SDL_Color* LightSkyBlue    ;
    static const SDL_Color* LightSlateGray  ;
    static const SDL_Color* LightSlateGrey  ;
    static const SDL_Color* LightSteelBlue  ;
    static const SDL_Color* LightYellow     ;
    static const SDL_Color* Lime   ; 
    static const SDL_Color* LimeGreen         ;
    static const SDL_Color* Linen             ;
    static const SDL_Color* Magenta           ;
    static const SDL_Color* Maroon            ;
    static const SDL_Color* MediumAquaMarine  ;
    static const SDL_Color* MediumBlue        ;
    static const SDL_Color* MediumOrchid      ;
    static const SDL_Color* MediumPurple      ;
    static const SDL_Color* MediumSeaGreen    ;
    static const SDL_Color* MediumSlateBlue   ;
    static const SDL_Color* MediumSpringGreen ;
    static const SDL_Color* MediumTurquoise   ;
    static const SDL_Color* MediumVioletRed   ;
    static const SDL_Color* MidnightBlue      ;
    static const SDL_Color* MintCream         ;
    static const SDL_Color* MistyRose         ;
    static const SDL_Color* Moccasin          ;
    static const SDL_Color* NavajoWhite       ;
    static const SDL_Color* Navy              ;
    static const SDL_Color* OldLace           ;
    static const SDL_Color* Olive             ;
    static const SDL_Color* OliveDrab         ;
    static const SDL_Color* Orange            ;
    static const SDL_Color* OrangeRed         ;
    static const SDL_Color* Orchid            ;
    static const SDL_Color* PaleGoldenRod     ;
    static const SDL_Color* PaleGreen         ;
    static const SDL_Color* PaleTurquoise     ;
    static const SDL_Color* PaleVioletRed     ;
    static const SDL_Color* PapayaWhip        ;
    static const SDL_Color* PeachPuff         ;
    static const SDL_Color* Peru              ;
    static const SDL_Color* Pink              ;
    static const SDL_Color* Plum              ;
    static const SDL_Color* PowderBlue        ;
    static const SDL_Color* Purple            ;
    static const SDL_Color* RebeccaPurple     ;
    static const SDL_Color* Red               ;
    static const SDL_Color* RosyBrown         ;
    static const SDL_Color* RoyalBlue         ;
    static const SDL_Color* SaddleBrown       ;
    static const SDL_Color* Salmon            ;
    static const SDL_Color* SandyBrown        ;
    static const SDL_Color* SeaGreen          ;
    static const SDL_Color* SeaShell          ;
    static const SDL_Color* Sienna            ;
    static const SDL_Color* Silver            ;
    static const SDL_Color* SkyBlue           ;
    static const SDL_Color* SlateBlue         ;
    static const SDL_Color* SlateGray         ;
    static const SDL_Color* SlateGrey         ;
    static const SDL_Color* Snow              ;
    static const SDL_Color* SpringGreen       ;
    static const SDL_Color* SteelBlue         ;
    static const SDL_Color* Tan               ;
    static const SDL_Color* Teal              ;
    static const SDL_Color* Thistle           ;
    static const SDL_Color* Tomato            ;
    static const SDL_Color* Turquoise         ;
    static const SDL_Color* Violet            ;
    static const SDL_Color* Wheat             ;
    static const SDL_Color* White             ;
    static const SDL_Color* WhiteSmoke        ;
    static const SDL_Color* Yellow            ;
    static const SDL_Color* YellowGreen       ;
};
#endif
