
#ifndef _SDL_COLOR_EXT_H_
#define _SDL_COLOR_EXT_H_

#include <wee/wee.hpp>
#include <stdint.h>
#include <SDL.h>

#define SDL_COLOR_(x) SDL_Color { (x & 0x00ff0000) >> 16, (x & 0x0000ff00) >> 8, (x & 0x000000ff), 0xff };

struct SDL_Color;

void SDL_CreateColorEXT(uint32_t, struct SDL_Color*);
void SDL_CreateColorRGB(uint8_t, uint8_t, uint8_t, struct SDL_Color*);
void SDL_CreateColorHSV(uint8_t, uint8_t, uint8_t, struct SDL_Color*);



struct SDL_ColorPresetEXT {
	constexpr static const SDL_Color AliceBlue =  SDL_COLOR_(0xF0F8FF);
	constexpr static const SDL_Color AntiqueWhite =  SDL_COLOR_(0xFAEBD7);
	constexpr static const SDL_Color Aqua =  SDL_COLOR_(0x00FFFF);
	constexpr static const SDL_Color Aquamarine =  SDL_COLOR_(0x7FFFD4);
	constexpr static const SDL_Color Azure =  SDL_COLOR_(0xF0FFFF);
	constexpr static const SDL_Color Beige =  SDL_COLOR_(0xF5F5DC);
	constexpr static const SDL_Color Bisque =  SDL_COLOR_(0xFFE4C4);
	constexpr static const SDL_Color Black =  SDL_COLOR_(0x000000);
	constexpr static const SDL_Color BlanchedAlmond =  SDL_COLOR_(0xFFEBCD);
	constexpr static const SDL_Color Blue =  SDL_COLOR_(0x0000FF);
	constexpr static const SDL_Color BlueViolet =  SDL_COLOR_(0x8A2BE2);
	constexpr static const SDL_Color Brown =  SDL_COLOR_(0xA52A2A);
	constexpr static const SDL_Color BurlyWood =  SDL_COLOR_(0xDEB887);
	constexpr static const SDL_Color CadetBlue =  SDL_COLOR_(0x5F9EA0);
	constexpr static const SDL_Color Chartreuse =  SDL_COLOR_(0x7FFF00);
	constexpr static const SDL_Color Chocolate =  SDL_COLOR_(0xD2691E);
	constexpr static const SDL_Color Coral =  SDL_COLOR_(0xFF7F50);
	constexpr static const SDL_Color CornflowerBlue =  SDL_COLOR_(0x6495ED);
	constexpr static const SDL_Color Cornsilk =  SDL_COLOR_(0xFFF8DC);
	constexpr static const SDL_Color Crimson =  SDL_COLOR_(0xDC143C);
	constexpr static const SDL_Color Cyan =  SDL_COLOR_(0x00FFFF);
	constexpr static const SDL_Color DarkBlue =  SDL_COLOR_(0x00008B);
	constexpr static const SDL_Color DarkCyan =  SDL_COLOR_(0x008B8B);
	constexpr static const SDL_Color DarkGoldenRod =  SDL_COLOR_(0xB8860B);
	constexpr static const SDL_Color DarkGray =  SDL_COLOR_(0xA9A9A9);
	constexpr static const SDL_Color DarkGrey =  SDL_COLOR_(0xA9A9A9);
	constexpr static const SDL_Color DarkGreen =  SDL_COLOR_(0x006400);
	constexpr static const SDL_Color DarkKhaki =  SDL_COLOR_(0xBDB76B);
	constexpr static const SDL_Color DarkMagenta =  SDL_COLOR_(0x8B008B);
	constexpr static const SDL_Color DarkOliveGreen =  SDL_COLOR_(0x556B2F);
	constexpr static const SDL_Color DarkOrange =  SDL_COLOR_(0xFF8C00);
	constexpr static const SDL_Color DarkOrchid =  SDL_COLOR_(0x9932CC);
	constexpr static const SDL_Color DarkRed =  SDL_COLOR_(0x8B0000);
	constexpr static const SDL_Color DarkSalmon =  SDL_COLOR_(0xE9967A);
	constexpr static const SDL_Color DarkSeaGreen =  SDL_COLOR_(0x8FBC8F);
	constexpr static const SDL_Color DarkSlateBlue =  SDL_COLOR_(0x483D8B);
	constexpr static const SDL_Color DarkSlateGray =  SDL_COLOR_(0x2F4F4F);
	constexpr static const SDL_Color DarkSlateGrey =  SDL_COLOR_(0x2F4F4F);
	constexpr static const SDL_Color DarkTurquoise =  SDL_COLOR_(0x00CED1);
	constexpr static const SDL_Color DarkViolet =  SDL_COLOR_(0x9400D3);
	constexpr static const SDL_Color DeepPink =  SDL_COLOR_(0xFF1493);
	constexpr static const SDL_Color DeepSkyBlue =  SDL_COLOR_(0x00BFFF);
	constexpr static const SDL_Color DimGray =  SDL_COLOR_(0x696969);
	constexpr static const SDL_Color DimGrey =  SDL_COLOR_(0x696969);
	constexpr static const SDL_Color DodgerBlue =  SDL_COLOR_(0x1E90FF);
	constexpr static const SDL_Color FireBrick =  SDL_COLOR_(0xB22222);
	constexpr static const SDL_Color FloralWhite =  SDL_COLOR_(0xFFFAF0);
	constexpr static const SDL_Color ForestGreen =  SDL_COLOR_(0x228B22);
	constexpr static const SDL_Color Fuchsia =  SDL_COLOR_(0xFF00FF);
	constexpr static const SDL_Color Gainsboro =  SDL_COLOR_(0xDCDCDC);
	constexpr static const SDL_Color GhostWhite =  SDL_COLOR_(0xF8F8FF);
	constexpr static const SDL_Color Gold =  SDL_COLOR_(0xFFD700);
	constexpr static const SDL_Color GoldenRod =  SDL_COLOR_(0xDAA520);
	constexpr static const SDL_Color Gray =  SDL_COLOR_(0x808080);
	constexpr static const SDL_Color Grey =  SDL_COLOR_(0x808080);
	constexpr static const SDL_Color Green =  SDL_COLOR_(0x008000);
	constexpr static const SDL_Color GreenYellow =  SDL_COLOR_(0xADFF2F);
	constexpr static const SDL_Color HoneyDew =  SDL_COLOR_(0xF0FFF0);
	constexpr static const SDL_Color HotPink =  SDL_COLOR_(0xFF69B4);
	constexpr static const SDL_Color IndianRed =  SDL_COLOR_(0xCD5C5C);
	constexpr static const SDL_Color Indigo =  SDL_COLOR_(0x4B0082);
	constexpr static const SDL_Color Ivory =  SDL_COLOR_(0xFFFFF0);
	constexpr static const SDL_Color Khaki =  SDL_COLOR_(0xF0E68C);
	constexpr static const SDL_Color Lavender =  SDL_COLOR_(0xE6E6FA);
	constexpr static const SDL_Color LavenderBlush =  SDL_COLOR_(0xFFF0F5);
	constexpr static const SDL_Color LawnGreen =  SDL_COLOR_(0x7CFC00);
	constexpr static const SDL_Color LemonChiffon =  SDL_COLOR_(0xFFFACD);
	constexpr static const SDL_Color LightBlue =  SDL_COLOR_(0xADD8E6);
	constexpr static const SDL_Color LightCoral =  SDL_COLOR_(0xF08080);
	constexpr static const SDL_Color LightCyan =  SDL_COLOR_(0xE0FFFF);
	constexpr static const SDL_Color LightGoldenRodYellow =  SDL_COLOR_(0xFAFAD2);
	constexpr static const SDL_Color LightGray =  SDL_COLOR_(0xD3D3D3);
	constexpr static const SDL_Color LightGrey =  SDL_COLOR_(0xD3D3D3);
	constexpr static const SDL_Color LightGreen =  SDL_COLOR_(0x90EE90);
	constexpr static const SDL_Color LightPink =  SDL_COLOR_(0xFFB6C1);
	constexpr static const SDL_Color LightSalmon =  SDL_COLOR_(0xFFA07A);
	constexpr static const SDL_Color LightSeaGreen =  SDL_COLOR_(0x20B2AA);
	constexpr static const SDL_Color LightSkyBlue =  SDL_COLOR_(0x87CEFA);
	constexpr static const SDL_Color LightSlateGray =  SDL_COLOR_(0x778899);
	constexpr static const SDL_Color LightSlateGrey =  SDL_COLOR_(0x778899);
	constexpr static const SDL_Color LightSteelBlue =  SDL_COLOR_(0xB0C4DE);
	constexpr static const SDL_Color LightYellow =  SDL_COLOR_(0xFFFFE0);
	constexpr static const SDL_Color Lime =  SDL_COLOR_(0x00FF00);
	constexpr static const SDL_Color LimeGreen =  SDL_COLOR_(0x32CD32);
	constexpr static const SDL_Color Linen =  SDL_COLOR_(0xFAF0E6);
	constexpr static const SDL_Color Magenta =  SDL_COLOR_(0xFF00FF);
	constexpr static const SDL_Color Maroon =  SDL_COLOR_(0x800000);
	constexpr static const SDL_Color MediumAquaMarine =  SDL_COLOR_(0x66CDAA);
	constexpr static const SDL_Color MediumBlue =  SDL_COLOR_(0x0000CD);
	constexpr static const SDL_Color MediumOrchid =  SDL_COLOR_(0xBA55D3);
	constexpr static const SDL_Color MediumPurple =  SDL_COLOR_(0x9370DB);
	constexpr static const SDL_Color MediumSeaGreen =  SDL_COLOR_(0x3CB371);
	constexpr static const SDL_Color MediumSlateBlue =  SDL_COLOR_(0x7B68EE);
	constexpr static const SDL_Color MediumSpringGreen =  SDL_COLOR_(0x00FA9A);
	constexpr static const SDL_Color MediumTurquoise =  SDL_COLOR_(0x48D1CC);
	constexpr static const SDL_Color MediumVioletRed =  SDL_COLOR_(0xC71585);
	constexpr static const SDL_Color MidnightBlue =  SDL_COLOR_(0x191970);
	constexpr static const SDL_Color MintCream =  SDL_COLOR_(0xF5FFFA);
	constexpr static const SDL_Color MistyRose =  SDL_COLOR_(0xFFE4E1);
	constexpr static const SDL_Color Moccasin =  SDL_COLOR_(0xFFE4B5);
	constexpr static const SDL_Color NavajoWhite =  SDL_COLOR_(0xFFDEAD);
	constexpr static const SDL_Color Navy =  SDL_COLOR_(0x000080);
	constexpr static const SDL_Color OldLace =  SDL_COLOR_(0xFDF5E6);
	constexpr static const SDL_Color Olive =  SDL_COLOR_(0x808000);
	constexpr static const SDL_Color OliveDrab =  SDL_COLOR_(0x6B8E23);
	constexpr static const SDL_Color Orange =  SDL_COLOR_(0xFFA500);
	constexpr static const SDL_Color OrangeRed =  SDL_COLOR_(0xFF4500);
	constexpr static const SDL_Color Orchid =  SDL_COLOR_(0xDA70D6);
	constexpr static const SDL_Color PaleGoldenRod =  SDL_COLOR_(0xEEE8AA);
	constexpr static const SDL_Color PaleGreen =  SDL_COLOR_(0x98FB98);
	constexpr static const SDL_Color PaleTurquoise =  SDL_COLOR_(0xAFEEEE);
	constexpr static const SDL_Color PaleVioletRed =  SDL_COLOR_(0xDB7093);
	constexpr static const SDL_Color PapayaWhip =  SDL_COLOR_(0xFFEFD5);
	constexpr static const SDL_Color PeachPuff =  SDL_COLOR_(0xFFDAB9);
	constexpr static const SDL_Color Peru =  SDL_COLOR_(0xCD853F);
	constexpr static const SDL_Color Pink =  SDL_COLOR_(0xFFC0CB);
	constexpr static const SDL_Color Plum =  SDL_COLOR_(0xDDA0DD);
	constexpr static const SDL_Color PowderBlue =  SDL_COLOR_(0xB0E0E6);
	constexpr static const SDL_Color Purple =  SDL_COLOR_(0x800080);
	constexpr static const SDL_Color RebeccaPurple =  SDL_COLOR_(0x663399);
	constexpr static const SDL_Color Red =  SDL_COLOR_(0xFF0000);
	constexpr static const SDL_Color RosyBrown =  SDL_COLOR_(0xBC8F8F);
	constexpr static const SDL_Color RoyalBlue =  SDL_COLOR_(0x4169E1);
	constexpr static const SDL_Color SaddleBrown =  SDL_COLOR_(0x8B4513);
	constexpr static const SDL_Color Salmon =  SDL_COLOR_(0xFA8072);
	constexpr static const SDL_Color SandyBrown =  SDL_COLOR_(0xF4A460);
	constexpr static const SDL_Color SeaGreen =  SDL_COLOR_(0x2E8B57);
	constexpr static const SDL_Color SeaShell =  SDL_COLOR_(0xFFF5EE);
	constexpr static const SDL_Color Sienna =  SDL_COLOR_(0xA0522D);
	constexpr static const SDL_Color Silver =  SDL_COLOR_(0xC0C0C0);
	constexpr static const SDL_Color SkyBlue =  SDL_COLOR_(0x87CEEB);
	constexpr static const SDL_Color SlateBlue =  SDL_COLOR_(0x6A5ACD);
	constexpr static const SDL_Color SlateGray =  SDL_COLOR_(0x708090);
	constexpr static const SDL_Color SlateGrey =  SDL_COLOR_(0x708090);
	constexpr static const SDL_Color Snow =  SDL_COLOR_(0xFFFAFA);
	constexpr static const SDL_Color SpringGreen =  SDL_COLOR_(0x00FF7F);
	constexpr static const SDL_Color SteelBlue =  SDL_COLOR_(0x4682B4);
	constexpr static const SDL_Color Tan =  SDL_COLOR_(0xD2B48C);
	constexpr static const SDL_Color Teal =  SDL_COLOR_(0x008080);
	constexpr static const SDL_Color Thistle =  SDL_COLOR_(0xD8BFD8);
	constexpr static const SDL_Color Tomato =  SDL_COLOR_(0xFF6347);
	constexpr static const SDL_Color Turquoise =  SDL_COLOR_(0x40E0D0);
	constexpr static const SDL_Color Violet =  SDL_COLOR_(0xEE82EE);
	constexpr static const SDL_Color Wheat =  SDL_COLOR_(0xF5DEB3);
	constexpr static const SDL_Color White =  SDL_COLOR_(0xFFFFFF);
	constexpr static const SDL_Color WhiteSmoke =  SDL_COLOR_(0xF5F5F5);
	constexpr static const SDL_Color Yellow =  SDL_COLOR_(0xFFFF00);
	constexpr static const SDL_Color YellowGreen =  SDL_COLOR_(0x9ACD32);

};
#endif
